package zetrixweb.com.bloodnow.extra;

import java.util.ArrayList;
import java.util.List;

public class IsoCountries {

    public static class IsoCountryInfo {
        String name;
        String numeric;
        String alpha2;
        String alpha3;
        String calling;
        String currency;
        String continent;

        public IsoCountryInfo(String name, String numeric, String alpha2, String alpha3, String calling, String currency, String continent)
        {
            this.name=name;
            this.numeric =numeric;
            this.alpha2=alpha2;
            this.alpha3 = alpha3;
            this.calling =calling;
            this.currency=currency;
            this.continent=continent;
        }
    }

    public List<IsoCountryInfo> allCountries;

    public IsoCountries()
    {
        allCountries = new ArrayList<>();
        allCountries.add(new IsoCountryInfo( "Afghanistan",  "004",  "AF",  "AFG",  "+93",  "AFN",  "AS"));
        allCountries.add(new IsoCountryInfo( "Åland Islands",  "248",  "AX",  "ALA",  "+358",  "FIM",  "EU") );
        allCountries.add(new IsoCountryInfo( "Albania",  "008",  "AL",  "ALB",  "+355",  "ALL",  "EU" ));
        allCountries.add(new IsoCountryInfo( "Algeria",  "012",  "DZ",  "DZA",  "+213",  "DZD",  "AF" ));
        allCountries.add(new IsoCountryInfo( "American Samoa",  "016",  "AS",  "ASM",  "+684",  "USD",  "OC" ));
        allCountries.add(new IsoCountryInfo( "Andorra",  "020",  "AD",  "AND",  "+376",  "EUR",  "EU" ));
        allCountries.add(new IsoCountryInfo( "Angola",  "024",  "AO",  "AGO",  "+244",  "AOA",  "AF" ));
        allCountries.add(new IsoCountryInfo( "Anguilla",  "660",  "AI",  "AIA",  "+264",  "XCD",  "NA" ));
        allCountries.add(new IsoCountryInfo( "Antarctica",  "010",  "AQ",  "ATA",  "+672",  "AUD",  "AN" ));
        allCountries.add(new IsoCountryInfo( "Antigua and Barbuda",  "028",  "AG",  "ATG",  "+268",  "XCD",  "NA" ));
        allCountries.add(new IsoCountryInfo( "Argentina",  "032",  "AR",  "ARG",  "+54",  "ARS",  "SA" ));
        allCountries.add(new IsoCountryInfo( "Armenia",  "051",  "AM",  "ARM",  "+374",  "AMD",  "AS" ));
        allCountries.add(new IsoCountryInfo( "Aruba",  "533",  "AW",  "ABW",  "+297",  "AWG",  "NA" ));
        allCountries.add(new IsoCountryInfo( "Australia",  "036",  "AU",  "AUS",  "+61",  "AUD",  "OC" ));
        allCountries.add(new IsoCountryInfo( "Austria",  "040",  "AT",  "AUT",  "+43",  "EUR",  "EU" ));
        allCountries.add(new IsoCountryInfo( "Azerbaijan",  "031",  "AZ",  "AZE",  "+994",  "AZN",  "AS" ));
        allCountries.add(new IsoCountryInfo( "Bahamas",  "044",  "BS",  "BHS",  "+242",  "BSD",  "NA" ));
        allCountries.add(new IsoCountryInfo( "Bahrain",  "048",  "BH",  "BHR",  "+973",  "BHD",  "AS" ));
        allCountries.add(new IsoCountryInfo( "Bangladesh",  "050",  "BD",  "BGD",  "+880",  "BDT",  "AS" ));
        allCountries.add(new IsoCountryInfo( "Barbados",  "052",  "BB",  "BRB",  "+246",  "BBD",  "NA" ));
        allCountries.add(new IsoCountryInfo( "Belarus",  "112",  "BY",  "BLR",  "+375",  "BYR",  "EU" ));
        allCountries.add(new IsoCountryInfo( "Belgium",  "056",  "BE",  "BEL",  "+32",  "EUR",  "EU" ));
        allCountries.add(new IsoCountryInfo( "Belize",  "084",  "BZ",  "BLZ",  "+501",  "BZD",  "NA" ));
        allCountries.add(new IsoCountryInfo( "Benin",  "204",  "BJ",  "BEN",  "+229",  "XOF",  "AF" ));
        allCountries.add(new IsoCountryInfo( "Bermuda",  "060",  "BM",  "BMU",  "+441",  "BMD",  "NA" ));
        allCountries.add(new IsoCountryInfo( "Bhutan",  "064",  "BT",  "BTN",  "+975",  "BTN",  "AS" ));
        allCountries.add(new IsoCountryInfo( "Bolivia, Plurinational State of",  "068",  "BO",  "BOL",  "+591",  "BOB",  "SA" ));
        allCountries.add(new IsoCountryInfo( "Bonaire, Sint Eustatius and Saba",  "535",  "BQ",  "BES",  "+599",  "USD",  "" ));
        allCountries.add(new IsoCountryInfo( "Bosnia and Herzegovina",  "070",  "BA",  "BIH",  "+387",  "BAM",  "EU" ));
        allCountries.add(new IsoCountryInfo( "Botswana",  "072",  "BW",  "BWA",  "+267",  "BWP",  "AF" ));
        allCountries.add(new IsoCountryInfo( "Bouvet Island",  "074",  "BV",  "BVT",  "+47",  "NOK",  "AN" ));
        allCountries.add(new IsoCountryInfo( "Brazil",  "076",  "BR",  "BRA",  "+55",  "BRL",  "SA" ));
        allCountries.add(new IsoCountryInfo( "British Indian Ocean Territory",  "086",  "IO",  "IOT",  "+246",  "USD",  "AS" ));
        allCountries.add(new IsoCountryInfo( "Brunei Darussalam",  "096",  "BN",  "BRN",  "+673",  "BND",  "AS" ));
        allCountries.add(new IsoCountryInfo( "Bulgaria",  "100",  "BG",  "BGR",  "+359",  "BGN",  "EU" ));
        allCountries.add(new IsoCountryInfo( "Burkina Faso",  "854",  "BF",  "BFA",  "+226",  "XOF",  "AF" ));
        allCountries.add(new IsoCountryInfo( "Burundi",  "108",  "BI",  "BDI",  "+257",  "BIF",  "AF" ));
        allCountries.add(new IsoCountryInfo( "Cambodia",  "116",  "KH",  "KHM",  "+855",  "KHR",  "AS" ));
        allCountries.add(new IsoCountryInfo( "Cameroon",  "120",  "CM",  "CMR",  "+237",  "XAF",  "AF" ));
        allCountries.add(new IsoCountryInfo( "Canada",  "124",  "CA",  "CAN",  "+1",  "CAD",  "NA" ));
        allCountries.add(new IsoCountryInfo( "Cabo Verde",  "132",  "CV",  "CPV",  "+238",  "CVE",  "AF" ));
        allCountries.add(new IsoCountryInfo( "Cayman Islands",  "136",  "KY",  "CYM",  "+345",  "KYD",  "NA" ));
        allCountries.add(new IsoCountryInfo( "Central African Republic",  "140",  "CF",  "CAF",  "+236",  "XAF",  "AF" ));
        allCountries.add(new IsoCountryInfo( "Chad",  "148",  "TD",  "TCD",  "+235",  "XAF",  "AF" ));
        allCountries.add(new IsoCountryInfo( "Chile",  "152",  "CL",  "CHL",  "+56",  "CLP",  "SA" ));
        allCountries.add(new IsoCountryInfo( "China",  "156",  "CN",  "CHN",  "+86",  "CNY",  "AS" ));
        allCountries.add(new IsoCountryInfo( "Christmas Island",  "162",  "CX",  "CXR",  "+61",  "AUD",  "AS" ));
        allCountries.add(new IsoCountryInfo( "Cocos (Keeling) Islands",  "166",  "CC",  "CCK",  "+891",  "AUD",  "AS" ));
        allCountries.add(new IsoCountryInfo( "Colombia",  "170",  "CO",  "COL",  "+57",  "COP",  "SA" ));
        allCountries.add(new IsoCountryInfo( "Comoros",  "174",  "KM",  "COM",  "+269",  "KMF",  "AF" ));
        allCountries.add(new IsoCountryInfo( "Congo",  "178",  "CG",  "COG",  "+242",  "XAF",  "AF" ));
        allCountries.add(new IsoCountryInfo( "Congo, the Democratic Republic of the",  "180",  "CD",  "COD",  "+243",  "CDF",  "AF" ));
        allCountries.add(new IsoCountryInfo( "Cook Islands",  "184",  "CK",  "COK",  "+682",  "NZD",  "OC" ));
        allCountries.add(new IsoCountryInfo( "Costa Rica",  "188",  "CR",  "CRI",  "+506",  "CRC",  "NA" ));
        allCountries.add(new IsoCountryInfo( "Côte d'Ivoire",  "384",  "CI",  "CIV",  "+225",  "XOF",  "AF" ));
        allCountries.add(new IsoCountryInfo( "Croatia",  "191",  "HR",  "HRV",  "+385",  "HRK",  "EU" ));
        allCountries.add(new IsoCountryInfo( "Cuba",  "192",  "CU",  "CUB",  "+53",  "CUP",  "NA" ));
        allCountries.add(new IsoCountryInfo( "Curaçao",  "531",  "CW",  "CUW",  "+599",  "ANG",  "" ));
        allCountries.add(new IsoCountryInfo( "Cyprus",  "196",  "CY",  "CYP",  "+357",  "EUR",  "AS" ));
        allCountries.add(new IsoCountryInfo( "Czech Republic",  "203",  "CZ",  "CZE",  "+420",  "CZK",  "EU" ));
        allCountries.add(new IsoCountryInfo( "Denmark",  "208",  "DK",  "DNK",  "+45",  "DKK",  "EU" ));
        allCountries.add(new IsoCountryInfo( "Djibouti",  "262",  "DJ",  "DJI",  "+253",  "DJF",  "AF" ));
        allCountries.add(new IsoCountryInfo( "Dominica",  "212",  "DM",  "DMA",  "+767",  "XCD",  "NA" ));
        allCountries.add(new IsoCountryInfo( "Dominican Republic",  "214",  "DO",  "DOM",  "+809",  "DOP",  "NA" ));
        allCountries.add(new IsoCountryInfo( "Ecuador",  "218",  "EC",  "ECU",  "+593",  "USD",  "SA" ));
        allCountries.add(new IsoCountryInfo( "Egypt",  "818",  "EG",  "EGY",  "+20",  "EGP",  "AF" ));
        allCountries.add(new IsoCountryInfo( "El Salvador",  "222",  "SV",  "SLV",  "+503",  "SVC",  "NA" ));
        allCountries.add(new IsoCountryInfo( "Equatorial Guinea",  "226",  "GQ",  "GNQ",  "+240",  "XAF",  "AF" ));
        allCountries.add(new IsoCountryInfo( "Eritrea",  "232",  "ER",  "ERI",  "+291",  "ETB",  "AF" ));
        allCountries.add(new IsoCountryInfo( "Estonia",  "233",  "EE",  "EST",  "+372",  "EUR",  "EU" ));
        allCountries.add(new IsoCountryInfo( "Ethiopia",  "231",  "ET",  "ETH",  "+251",  "ETB",  "AF" ));
        allCountries.add(new IsoCountryInfo( "Falkland Islands (Malvinas)",  "238",  "FK",  "FLK",  "+500",  "FKP",  "SA" ));
        allCountries.add(new IsoCountryInfo( "Faroe Islands",  "234",  "FO",  "FRO",  "+298",  "DKK",  "EU" ));
        allCountries.add(new IsoCountryInfo( "Fiji",  "242",  "FJ",  "FJI",  "+679",  "FJD",  "OC" ));
        allCountries.add(new IsoCountryInfo( "Finland",  "246",  "FI",  "FIN",  "+358",  "EUR",  "EU" ));
        allCountries.add(new IsoCountryInfo( "France",  "250",  "FR",  "FRA",  "+33",  "EUR",  "EU" ));
        allCountries.add(new IsoCountryInfo( "French Guiana",  "254",  "GF",  "GUF",  "+594",  "EUR",  "SA" ));
        allCountries.add(new IsoCountryInfo( "French Polynesia",  "258",  "PF",  "PYF",  "+689",  "XPF",  "OC" ));
        allCountries.add(new IsoCountryInfo( "French Southern Territories",  "260",  "TF",  "ATF",  "+689",  "EUR",  "AN" ));
        allCountries.add(new IsoCountryInfo( "Gabon",  "266",  "GA",  "GAB",  "+241",  "XAF",  "AF" ));
        allCountries.add(new IsoCountryInfo( "Gambia",  "270",  "GM",  "GMB",  "+220",  "GMD",  "AF" ));
        allCountries.add(new IsoCountryInfo( "Georgia",  "268",  "GE",  "GEO",  "+995",  "GEL",  "AS" ));
        allCountries.add(new IsoCountryInfo( "Germany",  "276",  "DE",  "DEU",  "+49",  "EUR",  "EU" ));
        allCountries.add(new IsoCountryInfo( "Ghana",  "288",  "GH",  "GHA",  "+233",  "GHS",  "AF" ));
        allCountries.add(new IsoCountryInfo( "Gibraltar",  "292",  "GI",  "GIB",  "+350",  "GIP",  "EU" ));
        allCountries.add(new IsoCountryInfo( "Greece",  "300",  "GR",  "GRC",  "+30",  "EUR",  "EU" ));
        allCountries.add(new IsoCountryInfo( "Greenland",  "304",  "GL",  "GRL",  "+299",  "DKK",  "NA" ));
        allCountries.add(new IsoCountryInfo( "Grenada",  "308",  "GD",  "GRD",  "+473",  "XCD",  "NA" ));
        allCountries.add(new IsoCountryInfo( "Guadeloupe",  "312",  "GP",  "GLP",  "+590",  "EUR",  "NA" ));
        allCountries.add(new IsoCountryInfo( "Guam",  "316",  "GU",  "GUM",  "+671",  "USD",  "OC" ));
        allCountries.add(new IsoCountryInfo( "Guatemala",  "320",  "GT",  "GTM",  "+502",  "GTQ",  "NA" ));
        allCountries.add(new IsoCountryInfo( "Guernsey",  "831",  "GG",  "GGY",  "+1481",  "GGP",  "EU" ));
        allCountries.add(new IsoCountryInfo( "Guinea",  "324",  "GN",  "GIN",  "+225",  "GNF",  "AF" ));
        allCountries.add(new IsoCountryInfo( "Guinea-Bissau",  "624",  "GW",  "GNB",  "+245",  "XOF",  "AF" ));
        allCountries.add(new IsoCountryInfo( "Guyana",  "328",  "GY",  "GUY",  "+592",  "GYD",  "SA" ));
        allCountries.add(new IsoCountryInfo( "Haiti",  "332",  "HT",  "HTI",  "+509",  "HTG",  "NA" ));
        allCountries.add(new IsoCountryInfo( "Heard Island and McDonald Islands",  "334",  "HM",  "HMD",  "+61",  "AUD",  "AN" ));
        allCountries.add(new IsoCountryInfo( "Holy See (Vatican City State)",  "336",  "VA",  "VAT",  "+379",  "EUR",  "EU" ));
        allCountries.add(new IsoCountryInfo( "Honduras",  "340",  "HN",  "HND",  "+504",  "HNL",  "NA" ));
        allCountries.add(new IsoCountryInfo( "Hong Kong",  "344",  "HK",  "HKG",  "+852",  "HKD",  "AS" ));
        allCountries.add(new IsoCountryInfo( "Hungary",  "348",  "HU",  "HUN",  "+36",  "HUF",  "EU" ));
        allCountries.add(new IsoCountryInfo( "Iceland",  "352",  "IS",  "ISL",  "+354",  "ISK",  "EU" ));
        allCountries.add(new IsoCountryInfo( "India",  "356",  "IN",  "IND",  "+91",  "INR",  "AS" ));
        allCountries.add(new IsoCountryInfo( "Indonesia",  "360",  "ID",  "IDN",  "+62",  "IDR",  "AS" ));
        allCountries.add(new IsoCountryInfo( "Iran, Islamic Republic of",  "364",  "IR",  "IRN",  "+98",  "IRR",  "AS" ));
        allCountries.add(new IsoCountryInfo( "Iraq",  "368",  "IQ",  "IRQ",  "+964",  "IQD",  "AS" ));
        allCountries.add(new IsoCountryInfo( "Ireland",  "372",  "IE",  "IRL",  "+353",  "EUR",  "EU" ));
        allCountries.add(new IsoCountryInfo( "Isle of Man",  "833",  "IM",  "IMN",  "+44",  "IMP",  "EU" ));
        allCountries.add(new IsoCountryInfo( "Israel",  "376",  "IL",  "ISR",  "+972",  "ILS",  "AS" ));
        allCountries.add(new IsoCountryInfo( "Italy",  "380",  "IT",  "ITA",  "+39",  "EUR",  "EU" ));
        allCountries.add(new IsoCountryInfo( "Jamaica",  "388",  "JM",  "JAM",  "+876",  "JMD",  "NA" ));
        allCountries.add(new IsoCountryInfo( "Japan",  "392",  "JP",  "JPN",  "+81",  "JPY",  "AS" ));
        allCountries.add(new IsoCountryInfo( "Jersey",  "832",  "JE",  "JEY",  "+44",  "JEP",  "EU" ));
        allCountries.add(new IsoCountryInfo( "Jordan",  "400",  "JO",  "JOR",  "+962",  "JOD",  "AS" ));
        allCountries.add(new IsoCountryInfo( "Kazakhstan",  "398",  "KZ",  "KAZ",  "+7",  "KZT",  "AS" ));
        allCountries.add(new IsoCountryInfo( "Kenya",  "404",  "KE",  "KEN",  "+254",  "KES",  "AF" ));
        allCountries.add(new IsoCountryInfo( "Kiribati",  "296",  "KI",  "KIR",  "+686",  "AUD",  "OC" ));
        allCountries.add(new IsoCountryInfo( "Korea, Democratic People's Republic of",  "408",  "KP",  "PRK",  "+850",  "KPW",  "AS" ));
        allCountries.add(new IsoCountryInfo( "Korea, Republic of",  "410",  "KR",  "KOR",  "+82",  "KRW",  "AS" ));
        allCountries.add(new IsoCountryInfo( "Kuwait",  "414",  "KW",  "KWT",  "+965",  "KWD",  "AS" ));
        allCountries.add(new IsoCountryInfo( "Kyrgyzstan",  "417",  "KG",  "KGZ",  "+996",  "KGS",  "AS" ));
        allCountries.add(new IsoCountryInfo( "Lao People's Democratic Republic",  "418",  "LA",  "LAO",  "+856",  "LAK",  "AS" ));
        allCountries.add(new IsoCountryInfo( "Latvia",  "428",  "LV",  "LVA",  "+371",  "EUR",  "EU" ));
        allCountries.add(new IsoCountryInfo( "Lebanon",  "422",  "LB",  "LBN",  "+961",  "LBP",  "AS" ));
        allCountries.add(new IsoCountryInfo( "Lesotho",  "426",  "LS",  "LSO",  "+266",  "LSL",  "AF" ));
        allCountries.add(new IsoCountryInfo( "Liberia",  "430",  "LR",  "LBR",  "+231",  "LRD",  "AF" ));
        allCountries.add(new IsoCountryInfo( "Libya",  "434",  "LY",  "LBY",  "+218",  "LYD",  "AF" ));
        allCountries.add(new IsoCountryInfo( "Liechtenstein",  "438",  "LI",  "LIE",  "+423",  "CHF",  "EU" ));
        allCountries.add(new IsoCountryInfo( "Lithuania",  "440",  "LT",  "LTU",  "+370",  "LTL",  "EU" ));
        allCountries.add(new IsoCountryInfo( "Luxembourg",  "442",  "LU",  "LUX",  "+352",  "EUR",  "EU" ));
        allCountries.add(new IsoCountryInfo( "Macao",  "446",  "MO",  "MAC",  "+853",  "MOP",  "AS" ));
        allCountries.add(new IsoCountryInfo( "Macedonia, the former Yugoslav Republic of",  "807",  "MK",  "MKD",  "+389",  "MKD",  "EU" ));
        allCountries.add(new IsoCountryInfo( "Madagascar",  "450",  "MG",  "MDG",  "+261",  "MGA",  "AF" ));
        allCountries.add(new IsoCountryInfo( "Malawi",  "454",  "MW",  "MWI",  "+265",  "MWK",  "AF" ));
        allCountries.add(new IsoCountryInfo( "Malaysia",  "458",  "MY",  "MYS",  "+60",  "MYR",  "AS" ));
        allCountries.add(new IsoCountryInfo( "Maldives",  "462",  "MV",  "MDV",  "+960",  "MVR",  "AS" ));
        allCountries.add(new IsoCountryInfo( "Mali",  "466",  "ML",  "MLI",  "+223",  "XOF",  "AF" ));
        allCountries.add(new IsoCountryInfo( "Malta",  "470",  "MT",  "MLT",  "+356",  "EUR",  "EU" ));
        allCountries.add(new IsoCountryInfo( "Marshall Islands",  "584",  "MH",  "MHL",  "+692",  "USD",  "OC" ));
        allCountries.add(new IsoCountryInfo( "Martinique",  "474",  "MQ",  "MTQ",  "+596",  "EUR",  "NA" ));
        allCountries.add(new IsoCountryInfo( "Mauritania",  "478",  "MR",  "MRT",  "+222",  "MRO",  "AF" ));
        allCountries.add(new IsoCountryInfo( "Mauritius",  "480",  "MU",  "MUS",  "+230",  "MUR",  "AF" ));
        allCountries.add(new IsoCountryInfo( "Mayotte",  "175",  "YT",  "MYT",  "+262",  "EUR",  "AF" ));
        allCountries.add(new IsoCountryInfo( "Mexico",  "484",  "MX",  "MEX",  "+52",  "MXN",  "NA" ));
        allCountries.add(new IsoCountryInfo( "Micronesia, Federated States of",  "583",  "FM",  "FSM",  "+691",  "USD",  "OC" ));
        allCountries.add(new IsoCountryInfo( "Moldova, Republic of",  "498",  "MD",  "MDA",  "+373",  "MDL",  "EU" ));
        allCountries.add(new IsoCountryInfo( "Monaco",  "492",  "MC",  "MCO",  "+355",  "EUR",  "EU" ));
        allCountries.add(new IsoCountryInfo( "Mongolia",  "496",  "MN",  "MNG",  "+976",  "MNT",  "AS" ));
        allCountries.add(new IsoCountryInfo( "Montenegro",  "499",  "ME",  "MNE",  "+382",  "EUR",  "EU" ));
        allCountries.add(new IsoCountryInfo( "Montserrat",  "500",  "MS",  "MSR",  "+664",  "XCD",  "NA" ));
        allCountries.add(new IsoCountryInfo( "Morocco",  "504",  "MA",  "MAR",  "+212",  "MAD",  "AF" ));
        allCountries.add(new IsoCountryInfo( "Mozambique",  "508",  "MZ",  "MOZ",  "+258",  "MZN",  "AF" ));
        allCountries.add(new IsoCountryInfo( "Myanmar",  "104",  "MM",  "MMR",  "+95",  "MMK",  "AS" ));
        allCountries.add(new IsoCountryInfo( "Namibia",  "516",  "NA",  "NAM",  "+264",  "NAD",  "AF" ));
        allCountries.add(new IsoCountryInfo( "Nauru",  "520",  "NR",  "NRU",  "+674",  "AUD",  "OC" ));
        allCountries.add(new IsoCountryInfo( "Nepal",  "524",  "NP",  "NPL",  "+977",  "NPR",  "AS" ));
        allCountries.add(new IsoCountryInfo( "Netherlands",  "528",  "NL",  "NLD",  "+31",  "EUR",  "EU" ));
        allCountries.add(new IsoCountryInfo( "New Caledonia",  "540",  "NC",  "NCL",  "+687",  "XPF",  "OC" ));
        allCountries.add(new IsoCountryInfo( "New Zealand",  "554",  "NZ",  "NZL",  "+64",  "NZD",  "OC" ));
        allCountries.add(new IsoCountryInfo( "Nicaragua",  "558",  "NI",  "NIC",  "+505",  "NIO",  "NA" ));
        allCountries.add(new IsoCountryInfo( "Niger",  "562",  "NE",  "NER",  "+277",  "XOF",  "AF" ));
        allCountries.add(new IsoCountryInfo( "Nigeria",  "566",  "NG",  "NGA",  "+234",  "NGN",  "AF" ));
        allCountries.add(new IsoCountryInfo( "Niue",  "570",  "NU",  "NIU",  "+683",  "NZD",  "OC" ));
        allCountries.add(new IsoCountryInfo( "Norfolk Island",  "574",  "NF",  "NFK",  "+672",  "AUD",  "OC" ));
        allCountries.add(new IsoCountryInfo( "Northern Mariana Islands",  "580",  "MP",  "MNP",  "+670",  "USD",  "OC" ));
        allCountries.add(new IsoCountryInfo( "Norway",  "578",  "NO",  "NOR",  "+47",  "NOK",  "EU" ));
        allCountries.add(new IsoCountryInfo( "Oman",  "512",  "OM",  "OMN",  "+968",  "OMR",  "AS" ));
        allCountries.add(new IsoCountryInfo( "Pakistan",  "586",  "PK",  "PAK",  "+92",  "PKR",  "AS" ));
        allCountries.add(new IsoCountryInfo( "Palau",  "585",  "PW",  "PLW",  "+680",  "USD",  "OC" ));
        allCountries.add(new IsoCountryInfo( "Palestine, State of",  "275",  "PS",  "PSE",  "+970",  "JOD",  "AS" ));
        allCountries.add(new IsoCountryInfo( "Panama",  "591",  "PA",  "PAN",  "+507",  "PAB",  "NA" ));
        allCountries.add(new IsoCountryInfo( "Papua New Guinea",  "598",  "PG",  "PNG",  "+675",  "PGK",  "OC" ));
        allCountries.add(new IsoCountryInfo( "Paraguay",  "600",  "PY",  "PRY",  "+595",  "PYG",  "SA" ));
        allCountries.add(new IsoCountryInfo( "Peru",  "604",  "PE",  "PER",  "+51",  "PEN",  "SA" ));
        allCountries.add(new IsoCountryInfo( "Philippines",  "608",  "PH",  "PHL",  "+63",  "PHP",  "AS" ));
        allCountries.add(new IsoCountryInfo( "Pitcairn",  "612",  "PN",  "PCN",  "+872",  "NZD",  "OC" ));
        allCountries.add(new IsoCountryInfo( "Poland",  "616",  "PL",  "POL",  "+48",  "PLN",  "EU" ));
        allCountries.add(new IsoCountryInfo( "Portugal",  "620",  "PT",  "PRT",  "+351",  "EUR",  "EU" ));
        allCountries.add(new IsoCountryInfo( "Puerto Rico",  "630",  "PR",  "PRI",  "+787",  "USD",  "NA" ));
        allCountries.add(new IsoCountryInfo( "Qatar",  "634",  "QA",  "QAT",  "+974",  "QAR",  "AS" ));
        allCountries.add(new IsoCountryInfo( "Réunion",  "638",  "RE",  "REU",  "+262",  "EUR",  "AF" ));
        allCountries.add(new IsoCountryInfo( "Romania",  "642",  "RO",  "ROU",  "+40",  "RON",  "EU" ));
        allCountries.add(new IsoCountryInfo( "Russian Federation",  "643",  "RU",  "RUS",  "+7",  "RUB",  "EU" ));
        allCountries.add(new IsoCountryInfo( "Rwanda",  "646",  "RW",  "RWA",  "+250",  "RWF",  "AF" ));
        allCountries.add(new IsoCountryInfo( "Saint Barthélemy",  "652",  "BL",  "BLM",  "+590",  "EUR",  "NA" ));
        allCountries.add(new IsoCountryInfo( "Saint Helena, Ascension and Tristan da Cunha",  "654",  "SH",  "SHN",  "+290",  "SHP",  "AF" ));
        allCountries.add(new IsoCountryInfo( "Saint Kitts and Nevis",  "659",  "KN",  "KNA",  "+869",  "XCD",  "NA" ));
        allCountries.add(new IsoCountryInfo( "Saint Lucia",  "662",  "LC",  "LCA",  "+758",  "XCD",  "NA" ));
        allCountries.add(new IsoCountryInfo( "Saint Martin (French part)",  "663",  "MF",  "MAF",  "+590",  "EUR",  "NA" ));
        allCountries.add(new IsoCountryInfo( "Saint Pierre and Miquelon",  "666",  "PM",  "SPM",  "+508",  "EUR",  "NA" ));
        allCountries.add(new IsoCountryInfo( "Saint Vincent and the Grenadines",  "670",  "VC",  "VCT",  "+784",  "XCD",  "NA" ));
        allCountries.add(new IsoCountryInfo( "Samoa",  "882",  "WS",  "WSM",  "+685",  "WST",  "OC" ));
        allCountries.add(new IsoCountryInfo( "San Marino",  "674",  "SM",  "SMR",  "+378",  "EUR",  "EU" ));
        allCountries.add(new IsoCountryInfo( "Sao Tome and Principe",  "678",  "ST",  "STP",  "+239",  "STD",  "AF" ));
        allCountries.add(new IsoCountryInfo( "Saudi Arabia",  "682",  "SA",  "SAU",  "+966",  "SAR",  "AS" ));
        allCountries.add(new IsoCountryInfo( "Senegal",  "686",  "SN",  "SEN",  "+221",  "XOF",  "AF" ));
        allCountries.add(new IsoCountryInfo( "Serbia",  "688",  "RS",  "SRB",  "+381",  "RSD",  "EU" ));
        allCountries.add(new IsoCountryInfo( "Seychelles",  "690",  "SC",  "SYC",  "+248",  "SCR",  "AF" ));
        allCountries.add(new IsoCountryInfo( "Sierra Leone",  "694",  "SL",  "SLE",  "+232",  "SLL",  "AF" ));
        allCountries.add(new IsoCountryInfo( "Singapore",  "702",  "SG",  "SGP",  "+65",  "SGD",  "AS" ));
        allCountries.add(new IsoCountryInfo( "Sint Maarten (Dutch part)",  "534",  "SX",  "SXM",  "+599",  "ANG",  "" ));
        allCountries.add(new IsoCountryInfo( "Slovakia",  "703",  "SK",  "SVK",  "+421",  "SKK",  "EU" ));
        allCountries.add(new IsoCountryInfo( "Slovenia",  "705",  "SI",  "SVN",  "+386",  "EUR",  "EU" ));
        allCountries.add(new IsoCountryInfo( "Solomon Islands",  "090",  "SB",  "SLB",  "+677",  "SBD",  "OC" ));
        allCountries.add(new IsoCountryInfo( "Somalia",  "706",  "SO",  "SOM",  "+252",  "SOS",  "AF" ));
        allCountries.add(new IsoCountryInfo( "South Africa",  "710",  "ZA",  "ZAF",  "+27",  "ZAR",  "AF" ));
        allCountries.add(new IsoCountryInfo( "South Georgia and the South Sandwich Islands",  "239",  "GS",  "SGS",  "+500",  "GBP",  "AN" ));
        allCountries.add(new IsoCountryInfo( "South Sudan",  "728",  "SS",  "SSD",  "+211",  "SSP",  "" ));
        allCountries.add(new IsoCountryInfo( "Spain",  "724",  "ES",  "ESP",  "+34",  "EUR",  "EU" ));
        allCountries.add(new IsoCountryInfo( "Sri Lanka",  "144",  "LK",  "LKA",  "+94",  "LKR",  "AS" ));
        allCountries.add(new IsoCountryInfo( "Sudan",  "729",  "SD",  "SDN",  "+249",  "SDG",  "AF" ));
        allCountries.add(new IsoCountryInfo( "Suriname",  "740",  "SR",  "SUR",  "+597",  "SRD",  "SA" ));
        allCountries.add(new IsoCountryInfo( "Svalbard and Jan Mayen",  "744",  "SJ",  "SJM",  "+47",  "NOK",  "EU" ));
        allCountries.add(new IsoCountryInfo( "Swaziland",  "748",  "SZ",  "SWZ",  "+268",  "CHF",  "AF" ));
        allCountries.add(new IsoCountryInfo( "Sweden",  "752",  "SE",  "SWE",  "+46",  "SEK",  "EU" ));
        allCountries.add(new IsoCountryInfo( "Switzerland",  "756",  "CH",  "CHE",  "+41",  "CHF",  "EU" ));
        allCountries.add(new IsoCountryInfo( "Syrian Arab Republic",  "760",  "SY",  "SYR",  "+963",  "SYP",  "AS" ));
        allCountries.add(new IsoCountryInfo( "Taiwan, Province of China",  "158",  "TW",  "TWN",  "+886",  "TWD",  "AS" ));
        allCountries.add(new IsoCountryInfo( "Tajikistan",  "762",  "TJ",  "TJK",  "+992",  "TJS",  "AS" ));
        allCountries.add(new IsoCountryInfo( "Tanzania, United Republic of",  "834",  "TZ",  "TZA",  "+255",  "TZS",  "AF" ));
        allCountries.add(new IsoCountryInfo( "Thailand",  "764",  "TH",  "THA",  "+66",  "THB",  "AS" ));
        allCountries.add(new IsoCountryInfo( "Timor-Leste",  "626",  "TL",  "TLS",  "+670",  "IDR",  "AS" ));
        allCountries.add(new IsoCountryInfo( "Togo",  "768",  "TG",  "TGO",  "+228",  "XOF",  "AF" ));
        allCountries.add(new IsoCountryInfo( "Tokelau",  "772",  "TK",  "TKL",  "+690",  "NZD",  "OC" ));
        allCountries.add(new IsoCountryInfo( "Tonga",  "776",  "TO",  "TON",  "+676",  "TOP",  "OC" ));
        allCountries.add(new IsoCountryInfo( "Trinidad and Tobago",  "780",  "TT",  "TTO",  "+868",  "TTD",  "NA" ));
        allCountries.add(new IsoCountryInfo( "Tunisia",  "788",  "TN",  "TUN",  "+216",  "TND",  "AF" ));
        allCountries.add(new IsoCountryInfo( "Turkey",  "792",  "TR",  "TUR",  "+90",  "TRY",  "EU" ));
        allCountries.add(new IsoCountryInfo( "Turkmenistan",  "795",  "TM",  "TKM",  "+993",  "TMM",  "AS" ));
        allCountries.add(new IsoCountryInfo( "Turks and Caicos Islands",  "796",  "TC",  "TCA",  "+649",  "USD",  "NA" ));
        allCountries.add(new IsoCountryInfo( "Tuvalu",  "798",  "TV",  "TUV",  "+688",  "TVD",  "OC" ));
        allCountries.add(new IsoCountryInfo( "Uganda",  "800",  "UG",  "UGA",  "+256",  "UGX",  "AF" ));
        allCountries.add(new IsoCountryInfo( "Ukraine",  "804",  "UA",  "UKR",  "+380",  "UAH",  "EU" ));
        allCountries.add(new IsoCountryInfo( "United Arab Emirates",  "784",  "AE",  "ARE",  "+971",  "AED",  "AS" ));
        allCountries.add(new IsoCountryInfo( "United Kingdom",  "826",  "GB",  "GBR",  "+44",  "GBP",  "EU" ));
        allCountries.add(new IsoCountryInfo( "United States",  "840",  "US",  "USA",  "+1",  "USD",  "NA" ));
        allCountries.add(new IsoCountryInfo( "United States Minor Outlying Islands",  "581",  "UM",  "UMI",  "+1",  "USD",  "OC" ));
        allCountries.add(new IsoCountryInfo( "Uruguay",  "858",  "UY",  "URY",  "+598",  "UYU",  "SA" ));
        allCountries.add(new IsoCountryInfo( "Uzbekistan",  "860",  "UZ",  "UZB",  "+998",  "UZS",  "AS" ));
        allCountries.add(new IsoCountryInfo( "Vanuatu",  "548",  "VU",  "VUT",  "+678",  "VUV",  "OC" ));
        allCountries.add(new IsoCountryInfo( "Venezuela, Bolivarian Republic of",  "862",  "VE",  "VEN",  "+58",  "VEF",  "SA" ));
        allCountries.add(new IsoCountryInfo( "Vietnam",  "704",  "VN",  "VNM",  "+84",  "VND",  "AS" ));
        allCountries.add(new IsoCountryInfo( "Virgin Islands, British",  "092",  "VG",  "VGB",  "+284",  "USD",  "NA" ));
        allCountries.add(new IsoCountryInfo( "Virgin Islands, U.S.",  "850",  "VI",  "VIR",  "+340",  "USD",  "NA" ));
        allCountries.add(new IsoCountryInfo( "Wallis and Futuna",  "876",  "WF",  "WLF",  "+681",  "XPF",  "OC" ));
        allCountries.add(new IsoCountryInfo( "Western Sahara",  "732",  "EH",  "ESH",  "+212",  "MAD",  "AF" ));
        allCountries.add(new IsoCountryInfo( "Yemen",  "887",  "YE",  "YEM",  "+967",  "YER",  "AS" ));
        allCountries.add(new IsoCountryInfo( "Zambia",  "894",  "ZM",  "ZMB",  "+260",  "ZMW",  "AF" ));
        allCountries.add(new IsoCountryInfo( "Zimbabwe",  "716",  "ZW",  "ZWE",  "+263",  "ZWD",  "AF" ));

    }
   
}